name: Build-Test-Deploy Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for building your Flask app and creating Docker container
      - name: Build Docker image
        run: docker build -t myflaskapp .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
            docker tag myflaskapp ${{ secrets.DOCKER_USERNAME }}/build:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/build:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for testing your Flask app
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/unit_tests.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy changes to dev branch
        run: |
            git push origin HEAD:${{ github.ref }}
